### ISSUE TITLE
Improving README.md

### ISSUE THREAD

**Issue by the-amazing-atharva** [sameem420/10ProjectsIn1HourChallenge#2]
Hello bro!!

I am a beginner web developer here and I found this repo while researching but I am very much interested in learning new things and also have done multiple documentation related open source contributions.

I would like to be assigned the task to improve the README.md for this repo

**Comment by sameem420** [comment]
sure please. I have assigned you the task.

**Comment by the-amazing-atharva** [comment]
Hey Thanks!!!

Will send a PR in sometime
